// TALENT-INTEL-1 (TI-1B) — the two AUTHORIZED résumé-source forms for the
// shared extraction orchestrator, plus the dependency-inversion port for the
// EDIT/re-extraction (ATTACHMENT) form.
//
// Ruling 15 (FIX_NOW): a client-supplied raw storage_key is NEVER the
// authorization anchor. The orchestrator accepts only these two typed source
// forms; authorization happens BEFORE any object-storage access, and the
// extraction core never resolves ownership from an arbitrary key.
//
//   - CREATE_DRAFT_UPLOAD: the TalentRecord/Attachment do not exist yet. The
//     fresh upload key was server-generated by Aramo's presign (E1). It is
//     validated deterministically (parseResumeObjectKey) against the A8-3a
//     convention + the authenticated tenant prefix. What this proves is EXACTLY:
//     "an Aramo-convention-compliant résumé key inside the authenticated
//     tenant's namespace" — NOT that this precise upload was issued to this
//     caller. No persisted draft_partition_id↔caller link exists today, so no
//     per-caller cryptographic binding is asserted or implied. It closes the
//     known cross-tenant read; the distinction stays explicit.
//     SITE: résumé objects are TENANT-scoped by design (A8-3a: the key carries
//     no site segment). @RequireSiteMatch() is present on the route but is inert
//     for it — the guard resolves a requested site only from a site_id
//     path-param/query, and this route carries neither (the key is in the body).
//     This matches the established stored-attachment download path, which is
//     likewise tenant-scoped (tenant-scoped findById + an inert site-match).
//     Attachment.site_id is row metadata, not an object-access boundary. If
//     product policy intends site-level object isolation for résumés, that is a
//     pre-existing lifecycle-wide gap, not introduced here.
//
//   - ATTACHMENT: an EXISTING Talent's stored résumé. Resolved via an OWNED
//     identifier (attachment_id) through the tenant-scoped attachment
//     repository, verifying owner_type=talent + owner_id=expected Talent +
//     is_resume, yielding the storage_key internally. The client never supplies
//     the authoritative storage_key on this path.

/**
 * The discriminated union of AUTHORIZED résumé sources. There is no generic
 * "raw storage_key" member by construction.
 */
export type ResumeExtractionSource =
  | {
      kind: 'CREATE_DRAFT_UPLOAD';
      /**
       * The opaque storage_key returned by the résumé-upload presign (E1).
       * Validated (tenant + namespace) before any object access; a raw key
       * outside the authenticated tenant's namespace is rejected pre-fetch.
       */
      storage_key: string;
    }
  | {
      kind: 'ATTACHMENT';
      /** An owned attachment id (the authorization anchor). */
      attachment_id: string;
      /** The Talent the attachment MUST belong to (owner_id binding). */
      talent_id: string;
    };

/**
 * The authenticated request context. Authorization is decided from THIS
 * (tenant/site established by the endpoint guards) plus the owned reference —
 * never from an arbitrary storage key.
 */
export interface AuthorizedExtractionContext {
  tenant_id: string;
  requestId: string;
}

/**
 * TI-1B dependency-inversion PORT for the ATTACHMENT source form.
 *
 * `attachment` already depends on `talent-record` (AttachmentRepository →
 * TalentRecordRepository), so talent-record MUST NOT import attachment (nx
 * cycle). The orchestrator therefore depends on this interface; the concrete
 * implementation (AttachmentResumeResolver) lives in `libs/attachment` and is
 * bound at the composition layer that owns the EDIT re-extraction consumer.
 */
export interface ResumeAttachmentResolver {
  /**
   * Resolve an owned attachment reference to its storage_key AFTER verifying
   * tenant + Talent ownership. Throws RESUME_SOURCE_UNAUTHORIZED (403) when the
   * attachment is absent in-tenant, not owned by the expected Talent, or not a
   * résumé. NEVER returns a key for an unauthorized reference.
   */
  resolveOwnedResumeStorageKey(input: {
    attachment_id: string;
    talent_id: string;
    tenant_id: string;
    requestId: string;
  }): Promise<{ storage_key: string }>;

  /**
   * TALENT-INTEL-1 TI-1D-C — resolve an owned résumé attachment to the metadata
   * an edition ingestion needs to mint its TalentDocument (storage_key + filename
   * + mime_type + size_bytes), AFTER the same tenant + Talent ownership + is_resume
   * checks as resolveOwnedResumeStorageKey. Throws RESUME_SOURCE_UNAUTHORIZED (403)
   * on any failure — the client never supplies these authoritative values.
   */
  resolveOwnedResume(input: {
    attachment_id: string;
    talent_id: string;
    tenant_id: string;
    requestId: string;
  }): Promise<{
    storage_key: string;
    filename: string;
    mime_type: string;
    size_bytes: number;
  }>;
}

/**
 * Injection token for the ATTACHMENT resolver port. A STRING token (not the
 * bare interface) is used deliberately: a module-local provider of a shared
 * class type collides with non-strict app.get lookups (a known substrate
 * trap). Consumers inject via `@Inject(RESUME_ATTACHMENT_RESOLVER)`.
 */
export const RESUME_ATTACHMENT_RESOLVER = 'RESUME_ATTACHMENT_RESOLVER';
