import { describe, expect, it } from 'vitest';

import {
  generatePlacementMigrationSql,
  generatePlacementOfferStateCollapseSql,
} from '../lib/generator/placement-sql-generator.js';

// L4-0 — the placement SQL generator owns TWO artifacts from one lifecycle source:
//   (1) the FROZEN historical init (regenerated byte-identical from the historical
//       snapshot — the placement:sql:check byte-gate covers that invariant), and
//   (2) a generator-owned FORWARD collapse migration that narrows the PlacementState enum.
// This proves the forward migration's shape: it narrows the enum via a FAIL-LOUD
// `::text::` type-swap, then CREATE-OR-REPLACEs the two affected guard function BODIES
// (the combined lifecycle guard + the T4-C assignment-aware one-live INSERT guard) to drop
// the stale OFFER_* literals — WITHOUT dropping or re-creating the triggers, so the
// Track 4 / T4-C trigger topology (lifecycle UPDATE-only + a separate BEFORE INSERT guard)
// is preserved. It is splitDdl-safe and leaves no OFFER_* literal anywhere.
describe('placement forward collapse migration generator (L4-0)', () => {
  const sql = generatePlacementOfferStateCollapseSql();

  it('narrows the enum via a fail-loud ::text:: type-swap (no silent map/coerce)', () => {
    expect(sql).toContain('CREATE TYPE "placement"."PlacementState_new" AS ENUM');
    expect(sql).toContain('USING ("state"::text::"placement"."PlacementState_new")');
    expect(sql).toContain('DROP TYPE "placement"."PlacementState"');
    expect(sql).toContain('ALTER TYPE "placement"."PlacementState_new" RENAME TO "PlacementState"');
  });

  it('CREATE-OR-REPLACEs BOTH guard function bodies (combined lifecycle + T4-C one-live)', () => {
    expect(sql).toContain(
      'CREATE OR REPLACE FUNCTION placement.enforce_placement_process_lifecycle()',
    );
    expect(sql).toContain(
      'CREATE OR REPLACE FUNCTION placement.enforce_placement_one_live_guard()',
    );
    // the collapsed one-live guard preserves the assignment-aware STARTED release
    expect(sql).toContain("existing.state = 'STARTED'");
    expect(sql).toContain("ca.lifecycle_state = 'ENDED'");
  });

  it('does NOT drop or re-create any trigger — T4-C binding topology is preserved', () => {
    expect(sql).not.toContain('DROP TRIGGER');
    expect(sql).not.toContain('CREATE TRIGGER');
    // never re-assert the pre-T4-C combined INSERT-OR-UPDATE binding
    expect(sql).not.toContain('BEFORE INSERT OR UPDATE');
  });

  it('leaves NO collapsed OFFER_* enum literal anywhere in the migration', () => {
    for (const legacy of ['OFFER_EXTENDED', 'OFFER_ACCEPTED', 'OFFER_DECLINED', 'OFFER_RESCINDED']) {
      // only as the fail-loud census target inside a comment; never as a live SQL literal
      expect(sql).not.toContain(`'${legacy}'`);
    }
    // the collapsed live NOT-IN list is exactly the two TERMINAL states
    expect(sql).toContain("NOT IN ('NO_SHOW', 'FELL_THROUGH')");
  });

  it('is splitDdl-safe: no ";" inside any "--" comment line', () => {
    for (const line of sql.split('\n')) {
      if (line.trimStart().startsWith('--')) expect(line).not.toContain(';');
    }
  });

  it('the frozen historical init still generates its enum + guard', () => {
    const init = generatePlacementMigrationSql();
    expect(init).toContain('CREATE TYPE "placement"."PlacementState" AS ENUM');
    expect(init).toContain('CREATE OR REPLACE FUNCTION placement.enforce_placement_process_lifecycle()');
  });
});
