import { describe, expect, it } from 'vitest';

import {
  generatePlacementMigrationSql,
  generatePlacementOfferStateCollapseSql,
} from '../lib/generator/placement-sql-generator.js';

// L4-0(a) — the placement SQL generator now owns TWO artifacts from one lifecycle source:
//   (1) the FROZEN historical init (regenerated byte-identical from the historical
//       snapshot — the placement:sql:check byte-gate covers that invariant), and
//   (2) a generator-owned FORWARD collapse migration that narrows the PlacementState enum.
// This proves the forward migration's shape: it DROPS then RECREATES the generator-owned
// lifecycle trigger (never hand-authored SQL) and narrows the enum via a FAIL-LOUD
// `::text::` type-swap, and is splitDdl-safe.
describe('placement forward collapse migration generator (L4-0)', () => {
  const sql = generatePlacementOfferStateCollapseSql();

  it('drops then recreates the generator-owned lifecycle trigger + function', () => {
    expect(sql).toContain('DROP TRIGGER IF EXISTS trg_enforce_placement_process_lifecycle');
    expect(sql).toContain(
      'DROP FUNCTION IF EXISTS placement.enforce_placement_process_lifecycle()',
    );
    expect(sql).toContain(
      'CREATE OR REPLACE FUNCTION placement.enforce_placement_process_lifecycle()',
    );
    expect(sql).toContain('CREATE TRIGGER trg_enforce_placement_process_lifecycle');
  });

  it('narrows the enum via a fail-loud ::text:: type-swap (no silent map/coerce)', () => {
    expect(sql).toContain('CREATE TYPE "placement"."PlacementState_new" AS ENUM');
    expect(sql).toContain('USING ("state"::text::"placement"."PlacementState_new")');
    expect(sql).toContain('DROP TYPE "placement"."PlacementState"');
    expect(sql).toContain('ALTER TYPE "placement"."PlacementState_new" RENAME TO "PlacementState"');
  });

  it('is splitDdl-safe: no ";" inside any "--" comment line', () => {
    for (const line of sql.split('\n')) {
      if (line.trimStart().startsWith('--')) expect(line).not.toContain(';');
    }
  });

  it('the frozen historical init still generates its enum + guard', () => {
    const init = generatePlacementMigrationSql();
    expect(init).toContain('CREATE TYPE "placement"."PlacementState" AS ENUM');
    expect(init).toContain('CREATE OR REPLACE FUNCTION placement.enforce_placement_process_lifecycle()');
  });
});
